// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cvngnqskjrtcubldhozb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN2bmducXNranJ0Y3VibGRob3piIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxNzk4MzEsImV4cCI6MjA1Nzc1NTgzMX0.LxgqJMHOWDucPHG6t8Bm6JmSuaDPPmDSOZ_fZepzLxY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);